repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
      - id: go-fmt
      - id: go-vet
      - id: go-cyclo
        args: [-over=15]
      - id: golangci-lint
  - repo: local
    hooks:
      - id: shfmt
        name: Format Shell Scripts
        entry: pls fmt:sh
        files: ^.*\.sh$
        pass_filenames: false
        language: system

      - id: cfg-scripts
        name: Configure Scripts
        entry: pls cfg:scripts
        files: ^.*\.sh$
        pass_filenames: false
        language: system

      - id: yaml-fmt
        name: Format YAML with prettier
        entry: pls fmt:yaml
        files: ^.*\.(yaml|yml)$
        pass_filenames: false
        language: system

      - id: md-fmt
        name: Format Markdown with prettier
        entry: pls fmt:md
        files: ^.*\.(MD|md)$
        pass_filenames: false
        language: system

      - id: nixpkgs-fmt
        name: Format NIX files
        entry: pls fmt:nix
        files: ^.*\.nix$
        language: system
        pass_filenames: false
